# Generated by Django 2.2.13 on 2020-07-06 14:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.CharField(help_text='For OBO ontologies, the value of this string MUST always be the official OBO ID, which is always equivalent to the ID prefix in lower case. For other resources use the prefix in identifiers.org.', max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The full name of the resource or ontology referred to by the id element.', max_length=200)),
                ('namespace_prefix', models.CharField(help_text='Prefix for objects from this resource. In the case of ontology resources, this should be the CURIE prefix.', max_length=200)),
                ('url', models.URLField(help_text='Resource URL. In the case of ontologies, this should be an OBO or OWL file. Other resources should link to the official or top-level url.')),
                ('version', models.CharField(help_text='The version of the resource or ontology used to make the annotation.', max_length=200)),
                ('iri_prefix', models.URLField(help_text='The IRI prefix, when used with the namespace prefix and an object ID, should resolve the term or object from the resource in question.')),
                ('extra_properties', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Extra properties that are not supported by current schema.', null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('namespace_prefix', 'version')},
            },
        ),
    ]
