version: '3'
services:
  minio-server:
    image: minio/minio:latest
    ports:
      - "9000:9000"
    command: ["server", "/data"]
  ga4gh-dos:
    build: ./lib/ga4gh-dos-schemas
  htsget-client:
    build: ./lib/htsget
