# tested on docker-engine 18.06.0
version: '3.7'

x-deploy:
  &default-restart
  restart_policy:
    delay: 10s
    max_attempts: 10
    window: 60s

services:
  minio-server:
    image: minio/minio:latest
    volumes:
      - ./etc/minio/data:/data
      - ./lib/minio/config:/root/.minioli
    networks:
      - traefik_net
    ports:
      - "9000:9000"
    environment:
      - MINIO_REGION: us-east-1
      - MINIO_DOMAIN: candig.com
    secrets:
      - source: minio_access_key
        target: acess_key
      - source: minio_secret_key
        target: secret_key
    deploy: *default-restart
    command: ["server", "/data"]

  ga4gh-dos:
    build: ./lib/ga4gh-dos-schemas
    image: ga4gh-drs-server:latest
    depends_on:
      - minio-server
    networks:
      - traefik_net
    deploy: *default-restart


  htsget-client:
    build: ./lib/htsget
    image: htsget-client:latest
    depends_on:
      - ga4gh-dos
    networks:
      - traefik_net
    deploy:  *default-restart

networks:
  traefik_net:
    external: true

secrets:
  minio_access_key:
    external: true
  minio_secret_key:
    external: true
