#!/usr/bin/env bash

set -Euo pipefail

if [[ $CANDIG_DEBUG_MODE -eq 0 ]]; then
    cp etc/env/example-production.env new.env
else
    cp etc/env/example.env new.env
fi

SED_MOD='-i.backup'
test=$(sed $SED_MOD s/test/test/ test.env 2> /dev/null)
if [[ $? -eq 1 ]]; then
    SED_MOD='-I .backup'
fi
if [ -f test.env ]; then
    rm test.env
fi

if [ -z "${FEDERATION_PROVINCE+x}" ]; then
    echo "Your province is not defined."
    read -r -p 'What is your provincial code? ' FEDERATION_PROVINCE
    case "$FEDERATION_PROVINCE" in
        AB|ab) FEDERATION_PROVINCE_CODE='ca-ab'; FEDERATION_PROVINCE='Alberta';;
        BC|bc) FEDERATION_PROVINCE_CODE='ca-bc'; FEDERATION_PROVINCE="British Columbia";;
        MB|mb) FEDERATION_PROVINCE_CODE='ca-mb'; FEDERATION_PROVINCE='Manitoba';;
        NB|nb) FEDERATION_PROVINCE_CODE='ca-nb'; FEDERATION_PROVINCE='New Brunswick';;
        NL|nl) FEDERATION_PROVINCE_CODE='ca-nl'; FEDERATION_PROVINCE='Newfoundland and Labrador';;
        NT|nt) FEDERATION_PROVINCE_CODE='ca-nt'; FEDERATION_PROVINCE='Northwest Territories';;
        NS|ns) FEDERATION_PROVINCE_CODE='ca-ns'; FEDERATION_PROVINCE='Nova Scotia';;
        NU|nu) FEDERATION_PROVINCE_CODE='ca-nu'; FEDERATION_PROVINCE='Nunavut';;
        ON|on) FEDERATION_PROVINCE_CODE='ca-on'; FEDERATION_PROVINCE='Ontario';;
        PE|pe) FEDERATION_PROVINCE_CODE='ca-pe'; FEDERATION_PROVINCE='Prince Edward Island';;
        QC|qc) FEDERATION_PROVINCE_CODE='ca-qc'; FEDERATION_PROVINCE='Quebec';;
        SK|sk) FEDERATION_PROVINCE_CODE='ca-sk'; FEDERATION_PROVINCE='Saskatchewan';;
        YT|yt) FEDERATION_PROVINCE_CODE='ca-yt'; FEDERATION_PROVINCE='Yukon';;
        *) echo 'Response not valid';;
    esac
fi

sed $SED_MOD s/CANDIG_DOMAIN=.*/CANDIG_DOMAIN=$CANDIG_DOMAIN/ new.env
sed $SED_MOD s/CANDIG_INTERNAL_DOMAIN=.*/CANDIG_INTERNAL_DOMAIN=${CANDIG_INTERNAL_DOMAIN}/ new.env
sed $SED_MOD s/CANDIG_AUTH_DOMAIN=.*/CANDIG_AUTH_DOMAIN=$CANDIG_AUTH_DOMAIN/ new.env
sed $SED_MOD s/CANDIG_SITE_LOCATION=.*/CANDIG_SITE_LOCATION=$CANDIG_SITE_LOCATION/ new.env
sed $SED_MOD s/CANDIG_DEBUG_MODE=.*/CANDIG_DEBUG_MODE=$CANDIG_DEBUG_MODE/ new.env
sed $SED_MOD s/LOCAL_IP_ADDR=.*/LOCAL_IP_ADDR=$LOCAL_IP_ADDR/ new.env
sed $SED_MOD s/VENV_OS=.*/VENV_OS=$VENV_OS/ new.env
sed $SED_MOD s/CANDIG_USER_KEY=.*/CANDIG_USER_KEY=$CANDIG_USER_KEY/ new.env
sed $SED_MOD s/KEEP_TEST_DATA=.*/KEEP_TEST_DATA=$KEEP_TEST_DATA/ new.env
sed $SED_MOD s@FEDERATION_SERVICE_URL=.*@FEDERATION_SERVICE_URL=$FEDERATION_SERVICE_URL@ new.env
sed $SED_MOD s/FEDERATION_SELF_SERVER_ID=.*/FEDERATION_SELF_SERVER_ID=$FEDERATION_SELF_SERVER_ID/ new.env
sed $SED_MOD "s/FEDERATION_PROVINCE=.*/FEDERATION_PROVINCE=${FEDERATION_PROVINCE}/" new.env
sed $SED_MOD s/FEDERATION_PROVINCE_CODE=.*/FEDERATION_PROVINCE_CODE=$FEDERATION_PROVINCE_CODE/ new.env
sed $SED_MOD s/KEYCLOAK_CLIENT_ID=.*/KEYCLOAK_CLIENT_ID=$KEYCLOAK_CLIENT_ID/ new.env
sed $SED_MOD s/KEYCLOAK_PORT=.*/KEYCLOAK_PORT=$KEYCLOAK_PORT/ new.env
sed $SED_MOD s/KEYCLOAK_HTTPS_PORT=.*/KEYCLOAK_HTTPS_PORT=$KEYCLOAK_HTTPS_PORT/ new.env
sed $SED_MOD s/KEYCLOAK_PUBLIC_PROTO=.*/KEYCLOAK_PUBLIC_PROTO=$KEYCLOAK_PUBLIC_PROTO/ new.env
sed $SED_MOD s/KEYCLOAK_PRIVATE_PROTO=.*/KEYCLOAK_PRIVATE_PROTO=$KEYCLOAK_PRIVATE_PROTO/ new.env
sed $SED_MOD s@KEYCLOAK_PUBLIC_URL=.*@KEYCLOAK_PUBLIC_URL=$KEYCLOAK_PUBLIC_URL@ new.env
sed $SED_MOD s@KEYCLOAK_PRIVATE_URL=.*@KEYCLOAK_PRIVATE_URL=$KEYCLOAK_PRIVATE_URL@ new.env
sed $SED_MOD s/KEYCLOAK_PROXY_HEADERS=.*/KEYCLOAK_PROXY_HEADERS=$KEYCLOAK_PROXY_HEADERS/ new.env
sed $SED_MOD s@TYK_LOGIN_TARGET_URL=.*@TYK_LOGIN_TARGET_URL=$TYK_LOGIN_TARGET_URL@ new.env
sed $SED_MOD s/TYK_ANALYTICS_FROM_EMAIL=.*/TYK_ANALYTICS_FROM_EMAIL=$TYK_ANALYTICS_FROM_EMAIL/ new.env
sed $SED_MOD s/TYK_USE_SSL=.*/TYK_USE_SSL=$TYK_USE_SSL/ new.env
sed $SED_MOD s/CANDIG_DATA_PORTAL_SUPPORT_EMAIL=.*/CANDIG_DATA_PORTAL_SUPPORT_EMAIL=$CANDIG_DATA_PORTAL_SUPPORT_EMAIL/ new.env
sed $SED_MOD s/ECS_DOMAIN=.*/ECS_DOMAIN=$ECS_DOMAIN/ new.env
sed $SED_MOD s/ECS_IP_ADDR=.*/ECS_IP_ADDR=$ECS_IP_ADDR/ new.env

if [ ! -z "${MOHCCN_SUPPORT_EMAIL+x}" ]; then
    sed $SED_MOD s/MOHCCN_SUPPORT_EMAIL=.*/MOHCCN_SUPPORT_EMAIL=$MOHCCN_SUPPORT_EMAIL/ new.env
fi


rm new.env.backup
mv .env env-7
mv new.env .env
