{
 "title": "Django Monitoring",
 "description": "Django with Prometheus and Grafana.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (django_http_requests_before_middlewares_total)"
    }
   ]
  },
  {
   "title": "Requests Per Status Code",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (django_http_responses_total_by_status_total) by(status)",
     "legendFormat": "HTTP Status: {{status}}"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view!~\"swagger-ui|schema|prometheus-django-metrics|<unnamed view>\"}",
     "legendFormat": "{{method}} {{view}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_sum{view!~\"swagger-ui|schema|prometheus-django-metrics|<unnamed view>\"} / django_http_requests_latency_seconds_by_view_method_count{view!~\"swagger-ui|schema|prometheus-django-metrics|<unnamed view>\"}",
     "legendFormat": "{{method}} {{view}}"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(view, method) (django_http_responses_total_by_status_view_method_total{status=~\"2.*\", view!~\"swagger-ui|schema|prometheus-django-metrics\"}) / sum by(view, method) (django_http_responses_total_by_status_view_method_total{view!~\"swagger-ui|schema|prometheus-django-metrics\"})",
     "legendFormat": "{{method}} {{view}} "
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(django_http_requests_latency_seconds_by_view_method_count{view!~\"swagger-ui|schema|prometheus-django-metrics|<unnamed view>\"}[1m])",
     "legendFormat": "{{method}} {{view}}"
    }
   ]
  },
  {
   "title": "Request Average Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_sum{view!~\"swagger-ui|schema|prometheus-django-metrics|<unnamed view>\"} / django_http_requests_latency_seconds_by_view_method_count{view!~\"swagger-ui|schema|prometheus-django-metrics|<unnamed view>\"}",
     "legendFormat": "{{method}} {{view}}"
    }
   ]
  },
  {
   "title": "Request Duration Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket[1d])) by (le))"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket[1d])) by (le))"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket[1d])) by (le))"
    }
   ]
  }
 ]
}