name: Test-CanDIG-build
run-name: Build Validation
on: [push]
jobs:
  Build-CanDIG:
    runs-on: [ubuntu-latest]
    defaults:
      run:
       shell: bash -l {0}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Grab example environment file
        run: cp etc/env/example.env .env
      - name: Display environment file
        run: cat ".env"
      - name: Add CanDIG local domain redirection to hosts
        run: echo "::1 candig.docker.internal" | sudo tee -a /etc/hosts
      - name: Install submodules
        run: git submodule update --init --recursive
      - name: Install CanDIG conda environment
        run: |
              make init-conda
              conda activate candig
      - name: Build stack
        run: make build-all
      - name: Integration testing
        run: make test-integration
